version: '3'

networks:
  django:
      driver: bridge

services:
    nginx:
        build: ./nginx
        ports:
            - 8000:80
        depends_on:
            - web
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - "web:web"
    db:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always
        environment:
            POSTGRES_USER:        postgres
            POSTGRES_PASSWORD:    postgres
            POSTGRES_DB:          thread_api
        networks:
            - django
    web:
        build: .
        environment:
          PYTHONBUFFERED: 1
        command: gunicorn --bind 0.0.0.0:8000 thread_api.wsgi:application
        image: thread_api
        links:
            - "db:db"
        volumes:
            - .:/code
        expose:
          - 8000
        depends_on:
            - db
        networks:
            - django
    prepare:
        command: bash -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python3 manage.py runcrons"
        volumes:
            - .:/code
        image: thread_api
        depends_on:
            - db
        links:
            - "db:db"
        networks:
            - django